import {
  Activity,
  Apple,
  Baby,
  Bean,
  Bone,
  Brain,
  Dna,
  Droplet,
  Droplets,
  Ear,
  Eye,
  FlaskConical,
  Heart,
  HeartHandshake,
  HeartPulse,
  Microscope,
  ScanFace,
  ScanSearch,
  Shield,
  ShieldCheck,
  Sparkles,
  Sprout,
  Stethoscope,
  Users,
  Wind,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const MAP: Record<string, LucideIcon> = {
  'heart-handshake': HeartHandshake,
  baby: Baby,
  microscope: Microscope,
  dna: Dna,
  brain: Brain,
  shield: Shield,
  'shield-check': ShieldCheck,
  'heart-pulse': HeartPulse,
  sparkles: Sparkles,
  ear: Ear,
  flask: FlaskConical,
  'flask-conical': FlaskConical,
  'flask-round': FlaskConical,
  stethoscope: Stethoscope,
  activity: Activity,
  heart: Heart,
  bone: Bone,
  kidney: Activity,
  eye: Eye,
  wind: Wind,
  users: Users,
  'scan-face': ScanFace,
  'scan-search': ScanSearch,
  droplet: Droplet,
  droplets: Droplets,
  apple: Apple,
  bean: Bean,
  zap: Zap,
  sprout: Sprout,
};

export function getCategoryIcon(icon: string): LucideIcon {
  return MAP[icon] || FlaskConical;
}
